import React from 'react';
import JobGrid from './JobGrid';
import { JobListing } from './JobComponents/JobCard'; // or your actual path
import image1 from '../../assets/job-title.png'; // example images

const jobData: JobListing[] = [
  
    {
        id: 1,
        image: image1,
        title: '案件タイトルタイトルタイトル',
        description: 'テキストテキストテキストテキストテキストテキストテキスト',
        location: '東京',
        salary: '報酬額：70万円〜90万円',
        type: ['業務委託'],
        tags: ['React', 'Next.js'],
        views: 120,
        applications: 8,
        postedDate: '2025-06-01',
        isNew: true,
        isFavorite: false,
        score: 90,
        skills: ['エンジニア'],
        subSkills: ['React', 'TypeScript'],
        projectType: '業務委託 / プロジェクト型',
        features: ['週3日', 'フルリモート'],
      },
      {
        id: 2,
        image: image1,
        title: '案件タイトルタイトルタイトル',
        description: 'テキストテキストテキストテキストテキストテキストテキスト',
        location: '東京',
        salary: '報酬額：70万円〜90万円',
        type: ['業務委託'],
        tags: ['React', 'Next.js'],
        views: 120,
        applications: 8,
        postedDate: '2025-06-01',
        isNew: true,
        isFavorite: false,
        score: 90,
        skills: ['エンジニア'],
        subSkills: ['React', 'TypeScript'],
        projectType: '業務委託 / プロジェクト型',
        features: ['週3日', 'フルリモート'],
      },
      {
        id: 3,
        image: image1,
        title: '案件タイトルタイトルタイトル',
        description: 'テキストテキストテキストテキストテキストテキストテキスト',
        location: '東京',
        salary: '報酬額：70万円〜90万円',
        type: ['業務委託'],
        tags: ['React', 'Next.js'],
        views: 120,
        applications: 8,
        postedDate: '2025-06-01',
        isNew: true,
        isFavorite: false,
        score: 90,
        skills: ['エンジニア'],
        subSkills: ['React', 'TypeScript'],
        projectType: '業務委託 / プロジェクト型',
        features: ['週3日', 'フルリモート'],
      },
      {
        id: 4,
        image: image1,
        title: '案件タイトルタイトルタイトル',
        description: 'テキストテキストテキストテキストテキストテキストテキスト',
        location: '東京',
        salary: '報酬額：70万円〜90万円',
        type: ['業務委託'],
        tags: ['React', 'Next.js'],
        views: 120,
        applications: 8,
        postedDate: '2025-06-01',
        isNew: true,
        isFavorite: false,
        score: 90,
        skills: ['エンジニア'],
        subSkills: ['React', 'TypeScript'],
        projectType: '業務委託 / プロジェクト型',
        features: ['週3日', 'フルリモート'],
      },
      {
        id: 5,
        image: image1,
        title: '案件タイトルタイトルタイトル',
        description: 'テキストテキストテキストテキストテキストテキストテキスト',
        location: '東京',
        salary: '報酬額：70万円〜90万円',
        type: ['業務委託'],
        tags: ['React', 'Next.js'],
        views: 120,
        applications: 8,
        postedDate: '2025-06-01',
        isNew: true,
        isFavorite: false,
        score: 90,
        skills: ['エンジニア'],
        subSkills: ['React', 'TypeScript'],
        projectType: '業務委託 / プロジェクト型',
        features: ['週3日', 'フルリモート'],
      },
      {
        id: 6,
        image: image1,
        title: '案件タイトルタイトルタイトル',
        description: 'テキストテキストテキストテキストテキストテキストテキスト',
        location: '東京',
        salary: '報酬額：70万円〜90万円',
        type: ['業務委託'],
        tags: ['React', 'Next.js'],
        views: 120,
        applications: 8,
        postedDate: '2025-06-01',
        isNew: true,
        isFavorite: false,
        score: 90,
        skills: ['エンジニア'],
        subSkills: ['React', 'TypeScript'],
        projectType: '業務委託 / プロジェクト型',
        features: ['週3日', 'フルリモート'],
      },

  // add more jobs
];

export default function JobsPage() {
  return <JobGrid jobs={jobData} />;
}
